### ISSUE TITLE
Sharing the source code of the project

### ISSUE THREAD

**Issue by DlmPierreDurand** [dracula/visual-basic-6#2]
Hello,

I have recently downloaded your fantastic tool, which will revolutionize my daily work routine in my small company. I have experimented with various ways to use the tool and I am now looking to customize it further to better assist me and my small team. Currently, the same color is being used to indicate changes in variables, functions, and their usage. Additionally, I am using a plugin called codeSmart to write code in VB6, and I would like to personalize it and its additions to the VB6 code.
Is it possible to have access to the source code ?

Best regards.

**Comment by jecsatta** [comment]
@DlmPierreDurand The colors used by VB6 are in the Windows Reg and embedded in exe . You can view the source in https://github.com/Ba11istix/VB-VBA-Colour-Change/
