### ISSUE TITLE
cant change BG

### ISSUE THREAD

**Issue by Avpman2** [dracula/visual-basic-6#3]
How do I change the background color of the VB6 IDE to match the sample image?

**Comment by Avpman2** [comment]
p.s. when I try to load the Dracula.ini I get an error _**"There was an error loading your file!"**_
How to fix?

**Comment by jecsatta** [comment]
@jvarrone 
Reopening to better investigate the issue 

https://github.com/dracula/visual-basic-6/commit/6cc4ac5e8fd6814d06132d339d3ffd8245994b09#commitcomment-131847936

Please provide the necessary steps to reproduce the issue.

Can you check the  the End of Line symbol of your Dracula.ini file?
![image](https://github.com/dracula/visual-basic-6/assets/60496134/df918cca-91f8-42e6-89e8-7edca03e10a5)

**Comment by Avpman2** [comment]
Looks like there are only LF (0A) and no CR (0D) in the file.

**Comment by Avpman2** [comment]
Running the UnixtoDos util fixed the loading issue. The text background color in the application is correct, but in VB IDE all text background is white. IDE background is also light gray instead of dark gray as in the application. Samples below. Please let me know if I need to re-send as attachments.

**Comment by jecsatta** [comment]
I can't see your attachements. What is the version of your vb6?
Please replace the ini content with text below and try to write again.

```
FF FE FB 00 
32 35 42 00 
44 47 5A 00 
8F ED FF 00 
50 FA 7B 00 
68 78 AA 00 
FF B8 6C 00 
80 80 00 00 
FF 7D C8 00 
00 80 00 00 
CE A3 FF 00 
00 80 80 00 
FF 55 55 00 
00 00 80 00 
F1 FA 8C 00 
FF FC F7 00 
2 6 13 3 16 2 2 2 3 3 
15 1 16 4 13 6 5 9 7 7 
```

**Comment by Avpman2** [comment]
Importing the data below fixed it. Everything looks like the sample now. BTW – Out of curiosity, where are these values stored in the PC??

 

Thanks!

**Comment by jecsatta** [comment]
the colors are updated by commit #5 and the .gitattributes file are now correcting the EOL.

**Comment by Avpman2** [comment]
Thank you, but what I meant was where are they stored in the PC? Meaning where does VB6 look for them?Sent from my Galaxy
-------- Original message --------From: Jean Andreatta ***@***.***> Date: 11/7/23  10:07 AM  (GMT-05:00) To: dracula/visual-basic-6 ***@***.***> Cc: jvarrone ***@***.***>, Mention ***@***.***> Subject: Re: [dracula/visual-basic-6] cant change BG (Issue #3) 
the colors are updated by commit #5 and the .gitattributes file are now correcting the EOL.
